POST https://localhost:4001/auth-login
Content-Type: application/json

{
    "numberPhone": "1233333333",
    "password": "admin@12"
}


//eqwewqewq
### get all users
GET http://localhost:4001/api/getUser

### get user by phone number
GET http://localhost:4001/api/get_user/find_number_phone/0967994184

###
GET http://localhost:4001/auth-login/0967994181/admin@123
###
GET http://localhost:4001/auth-login/0967994181/admin@123
###
GET http://localhost:4001/api/get_user/find_number_phone/0967994184
###
GET http://localhost:4001/api/get_user/find_number_phone/0967994184

###
GET http://localhost:4001/api/get_user/find_id_user/66cd7fc59cffefa1ad0fd503
###
GET http://localhost:4001/account/get_order-ticket-flight/66cd7fc59cffefa1ad0fd503
###
GET http://localhost:4001/order/get_order-ticket-flight/66d18531dbc4595710a1d949
###
POST http://localhost:4001/order/order-ticket_delete/flight_update
Content-Type: application/json

{
    "idDh": "66d3416cabda79265ab94095"
}
###
GET  http://localhost:4001/api/get_user/find_number_phone/0967994184
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOiI2NmU5MzlhZWQyZTI1NDNkODEwN2RlMGEiLCJpYXQiOjE3MjY2Nzc3MjQsImV4cCI6MTcyNjY4MTMyNH0.r8scQDlnsomW-d6w2OeTw_7uvlZefxwQ4swxq68UcGo


###
POST http://localhost:4001/order/run-time-pay-order
Content-Type: application/json

{
    "state": "true",
    "orderID": "66d415d5a5375dfcd972b531",
    "time": {
        "year": 2024,
        "month": 8,
        "date": 9,
        "hour": 15,
        "minute": 54,
        "second": 0
    }
}
###
GET http://localhost:4001/account/get_order-ticket-flight/66cd7fc59cffefa1ad0fd503

###
POST http://localhost:4001/order/order-ticket_create/flight_update
Content-Type: application/json

{
    "userId": "66cd7fc59cffefa1ad0fd503",
    "soLuongVe":"", 
    "tongGia":"",
    "trangThai":"",
    "tickets": [
        {
           "Ten": "qưe",
            "phoneNumber": "123456789",
    "soKyHanhLy": 2,
    "hangVe": "Vé thường",
    "giaVe": 2000000,

 
    "trangThaiVe": "Đã đặt"
        },
        {
           "Ten": "qưe",
            "phoneNumber": "123456789",
    "soKyHanhLy": 2,
    "hangVe": "Vé thường",
    "giaVe": 2000000,

 
    "trangThaiVe": "Đã đặtđâsdasaaaaaaaaa"
        },
        {
           "Ten": "qưe",
            "phoneNumber": "123456789",
    "soKyHanhLy": 2,
    "hangVe": "Vé thường",
    "giaVe": 2000000,

 
    "trangThaiVe": "Đã đặtđâsd"
        }
        
    ],
    "flightId":"669bd576a3ccd120eaeea7b3"
}

###
POST http://localhost:4001/payment-momo
Content-Type: application/json

{
    "orderId": "9999990112",
    "amount": "20000"
}
###
POST http://localhost:4001/api/update-status-donhang
Content-Type: application/json

{
    "orderID": "66d047ab77b213edc6079798",
    "status": 200
}

###
PATCH  http://localhost:4001/api/update_user/66cd7fc59cffefa1ad0fd503
Content-Type: application/json

{
    "numberPhone": "0967994184",
  "fullName": "ThanhLongFruit",
  "gender": "Nam",
  "birthday": "2004-04-15",
  "password": "admin@123",
  "status": "Đang hoạt động"

}

###
GET  http://localhost:4001/account/get_order-ticket-flight/66e939aed2e2543d8107de0a
###
GET  http://localhost:4001/order/del-orders-pending/66e939aed2e2543d8107de0a
###
GET   http://localhost:4001/transaction-status/66d415d5a5375dfcd972b531

